### ISSUE TITLE
Mistake in redame

### ISSUE THREAD

**Issue by migacz1125** [yadickson/gulp-font-npm-files#1]
> Usage with gulp
var gulp = require('gulp');
var styleNpmFiles = require('gulp-font-npm-files');

>gulp.task('TASKNAME', function() {
    return gulp.src(fontNpmFiles())
        .pipe(/* what you want to do with the files */)
});

should be fontNpmFiles intead of styleNpmFiles

**Comment by yadickson** [comment]
Thanks a lot.
